#!/bin/zsh
#https://gist.github.com/mitukiii/4234173
local tac
if which tac > /dev/null; then
    tac="tac"
else
    tac="tail -r"
fi
BUFFER=$(\history -n 1 | \
    eval $tac | \
    percol)
CURSOR=$#BUFFER
zle clear-screen
