#!/usr/bin/env zsh

# クリップボードへの書き込み。
# 標準入力があればそれを、なければ$CUTBUFFER(zshのkill-ring)を、
# `$DISPLAY`があればxsel、`$WAYLAND_DISPLAY`があれば`wl-copy`、
# どちらもなければOSC 52エスケープシーケンスで、
# クリップボードに書き込みます。
to-clipboard() {
  local content
  if [[ -t 0 ]]; then
    content=$CUTBUFFER          # zshのkill-ringを使います。
  else
    content=$(</dev/stdin)      # 標準入力がありそうなら使います。
  fi
  if [[ -n $DISPLAY ]] && hash xsel 2>/dev/null; then
    echo -n "$content" | xsel --clipboard --input --logfile /dev/null
  elif [[ -n $WAYLAND_DISPLAY ]] && hash wl-copy 2>/dev/null; then
    echo -n "$content" | wl-copy
  else
    local encoded=$(echo -n "$content" | base64 | tr -d '\n')
    printf '\e]52;c;%s\a' "$encoded"
  fi
}
