#!/usr/bin/env zsh

world="
@azu/github-label-setup
babel-cli
bash-language-server
dart-sass
eslint-cli
javascript-typescript-langserver
license
ocaml-language-server
prettier
typescript
yarn
"

echo $world|xargs yarn global add
