#!/usr/bin/env zsh

world="
@azu/github-label-setup
babel-cli
bash-language-server
eslint-cli
javascript-typescript-langserver
license
ocaml-language-server
prettier
sass
typescript
"

echo $world|xargs yarn --emoji true global add
