#default hack
alias 	 x='clamdscan --infected && extract'
alias -g ag='ag -i'
alias -g grep='grep -i'
alias -g history='fc -li -30'
alias -g make='make -j5'
alias -g nkf='nkf -w -Lu -d -x'
alias -g omake='omake -j5'
alias -g rsync-copy='rsync -av --progress -h'
alias -g sudo='sudo -E'
