alias a='sudo dispatch-conf'
alias d='dub --build=unittest'
alias ga='git add --all .'
alias m='sudo emerge -tv'
alias o='locate -i'
alias oo='locateCurrentDir'
alias oon='locateCurrentDirNull'
alias u='updatedb'
alias udn='sudo emerge -uDNt --with-bdeps=y world --keep-going'
alias x='aunpack --subdir'
alias z='exec zsh -l'

alias -g e='emacsclient --no-wait'
alias -g n='xdg-open'
alias -g p='less -N'
alias -g t='gvfs-trash'
