[character]
error_symbol = "[✖](bold red)"

[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
symbol = "🌱 "

[time]
disabled = false
format = "[$time]($style) "
time_format = "%Y-%m-%dT%H:%M:%S"
