alias a='sudo dispatch-conf'
alias d='dub --build=unittest'
alias ga='git add --all .'
alias m='sudo emerge -tv'
alias o='locate -i'
alias oo='locate-current-dir'
alias oon='locate-current-dir-null'
alias u='updatedb'
alias udn='sudo emerge -uDNt --with-bdeps=y world --keep-going'
alias x='aunpack'
alias z='exec zsh -l'

alias -g e='emacsclient --no-wait'
alias -g n='xdg-open'
alias -g p='less -N'
alias -g t='noglob gvfs-trash'
