alias a='aunpack'
alias c='cd $(readlink -f ~/Documents/current/)'
alias d='sudo dispatch-conf'
alias e='emacsclient --no-wait -a emacs'
alias m='sudo -E emerge'
alias n='sudo netstat -aepW|less'
alias o='xdg-open'
alias p='less'
alias s='sudo eselect'
alias t='trash'
alias u='sudo updatedb'
alias x='gtk-launch'
alias y='yarn start'
alias z='exec zsh'

alias bf='sudo btrfs filesystem'
alias bs='sudo btrfs subvolume'

alias eqa='equery --no-pipe a'
alias eqb='equery --no-pipe b'
alias eqc='equery --no-pipe c'
alias eqd='equery --no-pipe d'
alias eqf='equery --no-pipe f --tree'
alias eqg='equery --no-pipe g'
alias eqh='equery --no-pipe h'
alias eqk='equery --no-pipe k'
alias eql='equery --no-pipe l'
alias eqm='equery --no-pipe m'
alias eqs='equery --no-pipe s'
alias equ='equery --no-pipe u -i'
alias eqw='equery --no-pipe w'
alias eqy='equery --no-pipe y'

alias f='locate --ignore-case'
alias ff='locate-current-dir'

alias ga='git add --all .'
alias gc='git clean -dxi'
alias gd='git clone --verbose --recursive --jobs $(nproc) --depth=1 --shallow-submodules'
alias ge='git clone --verbose --recursive --jobs $(nproc)'
alias gf='git-add-file'
alias gl='git log'
alias gm='git commit -v -m'
alias gp='git push --verbose'
alias gq='git pull-request'
alias gs='git status'
alias gu='git pull --progress --all --keep'

alias gr='git reset --hard'
alias grh='git reset --hard HEAD'
alias grp='git reset --hard "HEAD^"'

alias jb='sudo journalctl -b'
alias je='sudo journalctl -e'

alias off='systemctl poweroff'
alias reb='systemctl reboot'
alias sus='systemctl suspend'

alias sdd='sudo systemctl disable'
alias sde='sudo systemctl enable'
alias sdf='sudo systemctl --failed --all'
alias sdi='sudo systemctl start'
alias sdk='sudo systemctl stop'
alias sdl='sudo systemctl daemon-reload'
alias sdn='sudo systemctl list-unit-files'
alias sdr='sudo systemctl restart'
alias sds='sudo systemctl status'
alias sdt='sudo systemctl list-timers'
alias sdu='systemctl --user'
