alias bat='batcat'
alias cp='cp --reflink=auto -p --verbose'
alias eix-diff='eix-diff -F'
alias eix-sync='sudo eix-sync -aM'
alias eix='eix -F'
alias make="make -j$(nproc)"
alias memory-compact='sudo memory-compact'
alias mv='mv --interactive --verbose'
alias parallel='parallel --no-notice'
alias sudo='sudo '
alias tree='tree -hlpCF --sort=version --dirsfirst'
