alias -g eix-sync='eix-sync -aM'
alias -g make='make -j8'
alias -g parallel='parallel --no-notice'
alias -g tree='tree -hlpCF --sort=version --dirsfirst'
alias eix-diff='eix-diff -F'
alias eix='eix -F'
