alias ls='\ls --color=auto   -AFhv'
alias  l='\ls --color=auto   -aFhv -l'
alias le='\ls --color=always -aFhv -l|less -N'

alias -g ag='ag -i'
alias -g e='emacsclient --no-wait'
alias -g n='xdg-open'
alias -g nkfu='nkf -w -x -Lu -d'
alias -g p='less'
alias -g t='mv --backup=numbered --target-directory=${HOME}/trash'
alias a='sudo dispatch-conf'
alias c9='clang -std=c99 -Wall -Werror -O0 -g'
alias cpy='clang++ -std=c++1y -stdlib=libc++ -Wall -Werror -O0 -g'
alias d='dub --build=unittest'
alias eix-diff='eix-diff -F'
alias eix='eix -F'
alias f='locate -i'
alias ff='locate-current-dir'
alias ffn='locate-current-dir-null'
alias fr='locate --regex'
alias fullpath='find `pwd` -maxdepth 1'
alias ga='git add --all .'
alias gc='git commit -v'
alias gp='git push'
alias grub-install='sudo mount /boot/efi && mkdirhier ~/backup/efi/ && tar cvfa ~/backup/efi/`date -I`.tar.xz /boot/efi && sudo grub2-install --target=x86_64-efi'
alias grub-update='sudo grub2-mkconfig -o /boot/grub/grub.cfg'
alias gst='git status'
alias m='sudo emerge -tv'
alias make='make -j8'
alias mozc-config='/usr/lib/mozc/mozc_tool -mode=config_dialog'
alias mozc-dict='/usr/lib/mozc/mozc_tool --mode=dictionary_tool'
alias pa='ps aux|ag'
alias pr='processing-java --run --force --output=tmp --sketch=main'
alias speexenc-high-all='echo *|xargs basename -s .wav|xargs -n 1 -P 16 -I filebasename speexenc --quality 10 --comp 10 --vbr filebasename.wav filebasename.spx'
alias speexenc-high='speexenc --quality 10 --comp 10 --vbr'
alias tree="tree -C"
alias u='updatedb'
alias udn='sudo zsh -c "emerge -uDNtv --with-bdeps y --keep-going y world || (haskell-updater && emerge -uDNtv --with-bdeps y --keep-going y world)"'
alias vscan='clamdscan * -r'
alias x='aunpack'
alias z='exec zsh -l'