alias f='locate -i'
alias ff='locate-current-dir'
alias ffn='locate-current-dir-null'
alias fr='locate -i --regex'

alias ga='git add --all .'
alias gc='git commit -v'
alias gp='git push'
alias gr='git reset --hard HEAD'
alias gs='git status'
alias gu='git pull'

alias eqa='equery a'
alias eqb='equery b'
alias eqc='equery c'
alias eqd='equery d'
alias eqf='equery f'
alias eqg='equery g'
alias eqh='equery h'
alias eqk='equery k'
alias eql='equery l'
alias eqm='equery m'
alias eqs='equery s'
alias equ='equery u'
alias eqw='equery w'
alias eqy='equery y'

alias off='systemctl poweroff'
alias reb='systemctl reboot'

alias sdb='sudo journalctl -b'

alias sdd='sudo systemctl disable'
alias sde='sudo systemctl enable'
alias sdf='sudo systemctl --failed --all'
alias sdi='sudo systemctl start'
alias sdk='sudo systemctl stop'
alias sdl='sudo systemctl daemon-reload'
alias sdr='sudo systemctl restart'
alias sds='sudo systemctl status'
alias sdu='sudo systemctl list-unit-files'

alias -g e='emacsclient --no-wait -a emacs'
alias -g p='less'
alias -g t='gvfs-trash'

alias c='cd ~/Documents/log/`date +"%Y_%m"`'
alias d='sudo dispatch-conf'
alias m='sudo emerge'
alias o='xdg-open'
alias u='updatedb'
alias x='gtk-launch'
alias z='exec zsh -l'
