alias -g e='emacsclient --no-wait -a emacs'
alias -g p='less'
alias -g t='mv --backup=numbered --target-directory=${HOME}/trash'
alias a='sudo dispatch-conf'
alias f='locate -i'
alias k='gtk-launch'
alias m='sudo emerge -tv'
alias n='xdg-open'
alias o='cd ~/Documents/log/`date +"%Y_%m"`'
alias u='updatedb'
alias x='aunpack'
alias z='exec zsh -l'
