alias -g e='emacsclient --no-wait -a emacs'
alias -g p='less'
alias -g t='mv --backup=numbered --target-directory=${HOME}/trash'
alias a='aunpack'
alias c='cd ~/Documents/log/`date +"%Y_%m"`'
alias d='sudo dispatch-conf'
alias f='locate -i'
alias m='sudo emerge -tv'
alias o='xdg-open'
alias u='updatedb'
alias x='gtk-launch'
alias z='exec zsh -l'
