alias f='locate -i'
alias ff='locate-current-dir'
alias ffn='locate-current-dir-null'
alias fr='locate -i --regex'

alias ga='git add --all .'
alias gc='git commit -v'
alias gp='git push'
alias gr='git reset --hard HEAD'
alias gs='git status'
alias gu='git pull'

alias eqa='equery --no-pipe a'
alias eqb='equery --no-pipe b'
alias eqc='equery --no-pipe c'
alias eqd='equery --no-pipe d'
alias eqf='equery --no-pipe f --tree'
alias eqg='equery --no-pipe g'
alias eqh='equery --no-pipe h'
alias eqk='equery --no-pipe k'
alias eql='equery --no-pipe l'
alias eqm='equery --no-pipe m'
alias eqs='equery --no-pipe s'
alias equ='equery --no-pipe u --ignore-linguas'
alias eqw='equery --no-pipe w'
alias eqy='equery --no-pipe y'

alias off='systemctl poweroff'
alias reb='systemctl reboot'

alias sdb='sudo journalctl -b'

alias sdd='sudo systemctl disable'
alias sde='sudo systemctl enable'
alias sdf='sudo systemctl --failed --all'
alias sdi='sudo systemctl start'
alias sdk='sudo systemctl stop'
alias sdl='sudo systemctl daemon-reload'
alias sdr='sudo systemctl restart'
alias sds='sudo systemctl status'
alias sdu='sudo systemctl list-unit-files'

alias -g e='emacsclient --no-wait -a emacs'
alias -g p='less'
alias -g t='gvfs-trash'

alias c='cd ~/Documents/log/`date +"%Y-%m"`'
alias d='sudo dispatch-conf'
alias m='sudo emerge'
alias o='xdg-open'
alias u='updatedb'
alias x='gtk-launch'
alias z='exec zsh -l'
