alias avifenc-base='avifenc --jobs all --speed 0'
alias avifenc-lossless='avifenc-base --lossless'
alias avifenc-lossy-base='avifenc-base --advanced aq-mode=1 --advanced enable-chroma-deltaq=1 --advanced enable-qm=1 --advanced qm-min=0 --advanced qm-max=15 --advanced deltaq-mode=3 --advanced end-usage=q'
alias avifenc-lossy-good='avifenc-lossy-base --advanced cq-level=18'
alias avifenc-lossy-lite='avifenc-lossy-base --advanced cq-level=32'
alias cwebp-lossy='cwebp -m 6 -mt -af -metadata all'
alias opusenc-speech='opusenc --speech --framesize 60'
alias oxipng-best='oxipng --opt max --strip safe --interlace 0 --zopfli'
